export enum THEME {
  BLUE = "BLUE",
  GRAY = "GRAY",
  BORDER_BLUE = "BORDER_BLUE",
}

export enum TABLE_ROW {
  EMAIL = "EMAIL",
  FIRST_NAME = "FIRST_NAME",
  LAST_NAME = "LAST_NAME",
  DATE_OF_BIRTH = "DATE_OF_BIRTH",
}

export enum ROLE {
  "ADMIN" = "ADMIN",
  "EMPLOYEE" = "EMPLOYEE",
  "SUPER_ADMIN" = "SUPER_ADMIN",
}
